// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxF-0yblHoFikVPDuwaOoCejkF98fIVM',
    appId: '1:635254369784:web:e1b0128eaa68e7237fba0d',
    messagingSenderId: '635254369784',
    projectId: 'flash-chat-1336d',
    authDomain: 'flash-chat-1336d.firebaseapp.com',
    storageBucket: 'flash-chat-1336d.appspot.com',
    measurementId: 'G-4HZ2E1KBWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOrSTy0WoszFd2qNkWgUrY2AeTuKFtsRk',
    appId: '1:635254369784:android:78849769207a291c7fba0d',
    messagingSenderId: '635254369784',
    projectId: 'flash-chat-1336d',
    storageBucket: 'flash-chat-1336d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHA-5iBjNjacCg_w0Hcwi-xpz94YrJVI0',
    appId: '1:635254369784:ios:ce81407b563ca8ae7fba0d',
    messagingSenderId: '635254369784',
    projectId: 'flash-chat-1336d',
    storageBucket: 'flash-chat-1336d.appspot.com',
    iosClientId: '635254369784-ej5nig3139it1upo9fdca19lk5vuafpv.apps.googleusercontent.com',
    iosBundleId: 'com.kitezeng.flashChat',
  );
}
